name: Deeproxio.UserManagement.API-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - "*"

pool: Development

variables:
- group: Local-Harbor-Registry
- name: buildConfiguration
  value: 'Release'
- name: ciImageTag
  value: 'ci-$(Build.BuildId)'
- name: helmRepositoryName
  value: 'dpio-user-management-api-chart'
- name: serviceImageName
  value: dpio-user-management-api
- name: migrationImageName
  value: dpio-user-management-api-db-migration
- name: releaseName
  value: user-management-api

stages:
  - stage: 'Build'
    displayName: 'Build API & Docker Images'
    jobs: 
    - job: 'Build'
      displayName: 'Build Deeproxio.UserManagement.API'
      pool: Development
      variables:
        dotnetSdkVersion: '3.1.x'
      steps:

      - task: UseDotNet@2
        inputs:
          version: '$(dotnetSdkVersion)'
          performMultiLevelLookup: true
        displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
        displayName: 'Restore NuGet dependencies'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--no-restore --configuration $(buildConfiguration)'
          projects: '**/*.csproj'
        displayName: 'Build Solution - $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '--configuration Debug --collect "Code coverage"'
        displayName: 'Run Unit Tests'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output publish'
          projects: '**/Deeproxio.UserManagement.API.csproj'
        displayName: 'Publish Deeproxio.UserManagement.API - $(buildConfiguration)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: publish
          ArtifactName: Deeproxio.UserManagement.API
        displayName: Publish Deeproxio.UserManagement.API Artifact

      - script: >-
          docker build -f ./Deeproxio.UserManagement.API/Dockerfile
          -t $(harbor_endpoint)/$(serviceImageName):latest
          -t $(harbor_endpoint)/$(serviceImageName):$(ciImageTag) .
        displayName: 'docker build (API)'

      - script: >-
          docker build -f ./Deeproxio.Persistence.Identity.Migration/Dockerfile
          -t $(harbor_endpoint)/$(migrationImageName):latest
          -t $(harbor_endpoint)/$(migrationImageName):$(ciImageTag) .
        displayName: 'docker build (Migration Job)'

      - script: >-
          docker login
          -u $(harbor_username)
          -p $(harbor_password)
          $(harbor_endpoint)
        displayName: 'docker login (Local Harbor Registry)'

      - script: >-
          docker push $(harbor_endpoint)/$(serviceImageName):$(ciImageTag) &&
          docker push $(harbor_endpoint)/$(migrationImageName):latest
        displayName: 'push docker image (API)'

      - script: >-
          docker push $(harbor_endpoint)/$(migrationImageName):$(ciImageTag) &&
          docker push $(harbor_endpoint)/$(migrationImageName):latest
        displayName: 'push docker image (Migration Job)'

      - script: >-
          helm lint ./chart/$(serviceImageName)
          --debug
          --logtostderr
        displayName: 'Helm Chart static analysis'
      
      - script: >-
          helm package ./chart/$(serviceImageName)
          --logtostderr
          --dependency-update
          --app-version $(ciImageTag)
          --destination $(Build.ArtifactStagingDirectory)
        displayName: 'Helm Chart package build'

      - script: >-
          helm registry login
          -u $(harbor_username)
          -p $(harbor_password)
          $(harbor_endpoint)
        displayName: 'helm login (Local Harbor Registry)'

      - script: >-
          helm chart save
          ./chart/$(serviceImageName)
          $(harbor_endpoint)/$(helmRepositoryName):$(ciImageTag)
        displayName: 'Save Helm Chart to Local Harbor Registry'

      - script: >-
          helm chart push
          $(harbor_endpoint)/$(helmRepositoryName):$(ciImageTag)
        displayName: 'Push Helm Chart to Local Harbor Registry'

      - publish: '$(Build.ArtifactStagingDirectory)'
        artifact: $(serviceImageName).helm-chart
        displayName: 'Upload Helm Build Artifacts'
  
  - stage: 'Local'
    displayName: 'Deploy to dpio-local environment'
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: Deploy
      pool: Development
      environment: dpio-local
      variables:
      - group: dpio-local-settings
      - group: dpio-platform-endpoint-paths
      strategy:
        runOnce:
          deploy:
            steps:

            - template: stage-deployment.yml
              parameters:
                harbor_username: $(harbor_username)
                harbor_password: $(harbor_password)
                harbor_endpoint: $(harbor_endpoint)
                helmRepositoryName: $(helmRepositoryName)
                serviceImageName: $(serviceImageName)
                migrationImageName: $(migrationImageName)
                ciImageTag: $(ciImageTag)
                imagePullSecretName: $(imagePullSecretName)
                namespace: $(namespace)
                host: $(host)
                tokenServicePath: $(tokenServicePath)
                secretKey: $(secretKey)
                releaseName: $(releaseName)


  - stage: 'Staging'
    displayName: 'Deploy to dpio-staging environment'
    dependsOn: Local
    condition: |
      and
      (
        succeeded(),
        or
        (
          eq(variables['Build.SourceBranchName'], 'develop'),
          eq(variables['Build.SourceBranchName'], 'master')
        )
      )
    jobs:
    - deployment: Deploy
      pool: Development
      environment: dpio-staging
      variables:
      - group: dpio-staging-settings
      - group: dpio-platform-endpoint-paths
      strategy:
        runOnce:
          deploy:
            steps:

            - template: stage-deployment.yml
              parameters:
                harbor_username: $(harbor_username)
                harbor_password: $(harbor_password)
                harbor_endpoint: $(harbor_endpoint)
                helmRepositoryName: $(helmRepositoryName)
                serviceImageName: $(serviceImageName)
                migrationImageName: $(migrationImageName)
                ciImageTag: $(ciImageTag)
                imagePullSecretName: $(imagePullSecretName)
                namespace: $(namespace)
                host: $(host)
                tokenServicePath: $(tokenServicePath)
                secretKey: $(secretKey)
                releaseName: $(releaseName)
