apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dpio-user-management-api.fullname" . }}
  labels:
    {{- include "dpio-user-management-api.labels" . | nindent 4 }}
data:
  jwt.audience: {{ .Values.jwt.audience }}
  jwt.issuer: {{ .Values.jwt.issuer }}
  {{- if .Values.prometheus.enabled }}
  metrics.prometheus.pushgateway.url: {{ .Values.prometheus.pushgateway.url }}
  {{- end -}}
