{{- $connectionString := printf "Host=%s;Port=%s;Database=%s;Username=%s;Password=%s" .Values.postgresql.fullnameOverride (.Values.postgresql.servicePort | quote) .Values.postgresql.accountDbName .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dpio-user-management-api.fullname" . }}-secrets
  labels:
    {{- include "dpio-user-management-api.labels" . | nindent 4 }}
type: Opaque
data:
  SecretKey: {{ .Values.secretKey | b64enc | quote }}
  PlatformIdentityDbContext: {{ $connectionString | b64enc | quote }}
  ConfigurationStoreDbContext: {{ $connectionString | b64enc | quote }}
  PersistedGrantStoreDbContext: {{ $connectionString | b64enc | quote }}
  PostgresHost: {{ .Values.postgresql.fullnameOverride | b64enc | quote }}
  PostgresPort: {{ .Values.postgresql.servicePort | quote | b64enc | quote }}
  PostgresDatabase: {{ .Values.postgresql.accountDbName | b64enc | quote }}
  PostgresUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  PostgresPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
